server:
  port: 8078

spring:
  application:
    name: llm-friend-memory-organizer
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: myTh0ughtsAreMine! # highly unsecure but it's a demo
  ai:
    ollama:
      chat:
        # model: mistral:7b-instruct-v0.3-q8_0
        # model: deepseek-r1:14b
        # model: deepseek-r1:8b
        # model: llama3.1:8b
        # model: llama3.2:3b
        # model: deepseek-r1:1.5b
        model: gemma3:12b
      embedding:
        model: nomic-embed-text
    vectorstore:
      neo4j:
        initialize-schema: true
        database-name: neo4j
        index-name: memory-index
        dimensions: 768
        distance-type: cosine
        batching-strategy: 100
  docker:
    compose:
      readiness:
        timeout: 5m
      wait:
        log-patterns:
          neo4j: "Started."
      lifecycle-management: start_only

de:
  sven:
    bayer:
      llm:
        friend:
          chatbot:
            llmName: Lumi
            maxSummarizationLength: 30
