Describe the message of the user.
Extract summarized information elements of the message.
Summarize and split the user's message into individual sentences that describe the information of the message.
Rules to follow:
- Each sentence includes only one statement.
- Always describe who is doing what in the sentence with an object. Do not use pronouns but instead the name of the person. Do not use "he," "she," or "they".
- Describe the message of the user in sentences.
- Create a enumerated list of sentences.
- Ensure to always keep the time and place within one statement.

The following is just example input that you can use to understand the task but do not take it as input data for your output:
Hello, my name is John. I like to play soccer with my brother James. After that, I went cycling with my wife on my bike in the park. I went to Venice last year in February.

The following is just example output that helps you understand the task but do not take it as output data:
1. The user's name is John.
2. The user likes to play soccer.
3. The user played soccer with his brother.
4. The user has a brother named James.
5. The user went cycling in the park with his wife.
6. The user has a bike.
7. The user went to Venice last year in February.

---
User’s message: "{userMessage}"
---